name: python39
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.13
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.6.0
      - cmake==3.28.3
      - contourpy==1.2.0
      - cycler==0.12.1
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - filelock==3.13.1
      - flash-attn==2.5.6
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - importlib-resources==6.1.3
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - lit==17.0.6
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - pandas==2.2.1
      - pillow==10.2.0
      - pip==24.0
      - pluggy==1.4.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scipy==1.12.0
      - six==1.16.0
      - sympy==1.12
      - tomli==2.0.1
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - triton==2.2.0
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - wget==3.2
      - zipp==3.17.0
